*********************************************************************************
* DynoSprite - music-stubs.asm
* Copyright (c) 2026, Space Bandits contributors
* All rights reserved.
*
* Music engine stubs residing in the secondary code page ($E000).
* These swap the tertiary music code page into $C000-$DFFF via $FFA6,
* call the implementation, then restore the previous page mapping.
*
* Music_WaveTable remains here (secondary page) because it is accessed by
* Music_RefillBuffer during FIRQ, when $C000 may have sprite erase data mapped.
*********************************************************************************

MUSIC_CODE_PHYS_PAGE    EQU     $3A     * physical page for music code (loaded at $4000)


***********************************************************
* Music_Start (stub)
*   Swap in the music code page and call Music_Start_Impl.
*
* - IN:      D = Phase increment (frequency * 65536 / AudioSamplingRate)
* - OUT:     none
* - Trashed: A, B, X, Y, U
***********************************************************
*
Music_Start
            pshs        a                   * save A (high byte of D parameter)
            lda         $FFA6               * read current $C000-$DFFF page
            pshs        a                   * save it on stack
            lda         #MUSIC_CODE_PHYS_PAGE
            sta         $FFA6               * map music code page to $C000
            lda         1,s                 * restore original A from stack
            jsr         Music_Start_Impl    * call implementation at $C000 with D intact
            puls        a                   * restore saved $FFA6 value
            sta         $FFA6               * restore previous $C000-$DFFF mapping
            puls        a,pc                * discard saved A and return


***********************************************************
* Music_Stop (stub)
*   Swap in the music code page and call Music_Stop_Impl.
*
* - IN:      none
* - OUT:     none
* - Trashed: A
***********************************************************
*
Music_Stop
            lda         $FFA6               * read current $C000-$DFFF page
            pshs        a                   * save it on stack
            lda         #MUSIC_CODE_PHYS_PAGE
            sta         $FFA6               * map music code page to $C000
            jsr         Music_Stop_Impl     * call implementation at $C000
            puls        a                   * restore saved $FFA6 value
            sta         $FFA6               * restore previous $C000-$DFFF mapping
            rts


***********************************************************
* Music_WaveTable
*   128-byte half sine wave lookup table (first half only).
*   Values range from $80 (center) up to $B0 (peak) and back.
*   The second half of the waveform is generated by negating
*   (two's complement) the lookup value, since the sine wave
*   is symmetric: sample[128+i] = $100 - sample[i].
*
*   This MUST remain in the secondary code page because
*   Music_RefillBuffer (primary page, FIRQ context) references it
*   and $C000 may not have the music code page mapped at that time.
***********************************************************
*
Music_WaveTable
            fcb     $80,$81,$82,$84,$85,$86,$87,$88,$89,$8B,$8C,$8D,$8E,$8F,$90,$91
            fcb     $92,$93,$95,$96,$97,$98,$99,$9A,$9B,$9C,$9D,$9E,$9E,$9F,$A0,$A1
            fcb     $A2,$A3,$A4,$A4,$A5,$A6,$A7,$A7,$A8,$A9,$A9,$AA,$AA,$AB,$AB,$AC
            fcb     $AC,$AD,$AD,$AE,$AE,$AE,$AF,$AF,$AF,$AF,$AF,$B0,$B0,$B0,$B0,$B0
            fcb     $B0,$B0,$B0,$B0,$B0,$B0,$AF,$AF,$AF,$AF,$AF,$AE,$AE,$AE,$AD,$AD
            fcb     $AC,$AC,$AB,$AB,$AA,$AA,$A9,$A9,$A8,$A7,$A7,$A6,$A5,$A4,$A4,$A3
            fcb     $A2,$A1,$A0,$9F,$9E,$9E,$9D,$9C,$9B,$9A,$99,$98,$97,$96,$95,$93
            fcb     $92,$91,$90,$8F,$8E,$8D,$8C,$8B,$89,$88,$87,$86,$85,$84,$82,$81

