name: Build

on:
  - push

jobs:
  build-dsk-images:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build
        run: ./forge all

  build-and-test-macos:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1

      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest

      - name: Build and test macOS application
        run: |
          xcodebuild -project Space\ Bandits/Space\ Bandits.xcodeproj -scheme "Space Bandits GitHub" test
          xcodebuild -project Space\ Bandits/Space\ Bandits.xcodeproj -scheme "Space Bandits" build CONFIGURATION_BUILD_DIR=`pwd`/build
