name: Make a New Release

on:
  push:
    tags:
      - '*'

jobs:
  build-6809-dsk-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build *.dsk images
        run: ./forge all

      - name: 'Upload 6809 *.dsk Images'
        uses: actions/upload-artifact@v2
        with:
          name: 6809-dsk-image
          path: build/*.DSK
          retention-days: 1

  build-6309-dsk-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build *.dsk images
        run: ./forge CPU=6309 all

      - name: 'Upload 6309 *.dsk Images'
        uses: actions/upload-artifact@v2
        with:
          name: 6309-dsk-image
          path: build/*.DSK
          retention-days: 1
 
  build-macos:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1

      - name: Build and test macOS application
        env:
          DEVELOPER_DIR: /Applications/Xcode_11.7.app/Contents/Developer
        run: |
          xcodebuild -project Space\ Bandits/Space\ Bandits.xcodeproj -configuration Release -scheme "Space Bandits" build CONFIGURATION_BUILD_DIR=`pwd`/build
          cd build
          tar cvf space-bandits.tgz *.app

      - name: 'Upload Tar Ball Apps'
        uses: actions/upload-artifact@v2
        with:
          name: tar-ball-apps
          path: build/*.tgz
          retention-days: 1

  upload-artifacts:
    runs-on: ubuntu-latest
    needs: [build-6809-dsk-image, build-6309-dsk-image, build-macos]
    steps:
      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v2

      - name: Get the tag
        run: |
          echo "RELEASE_TAG=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
          echo "REPO_NAME=${GITHUB_REPOSITORY#*/}" >> $GITHUB_ENV

      - name: Create a release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: "./6809-dsk-image/*.DSK,./6309-dsk-image/*.DSK,./tar-ball-apps/*.tgz"
          allowUpdates: true
          draft: true
          name: "${{ format('{0} {1}', env.REPO_NAME, env.RELEASE_TAG) }}"
